### ISSUE TITLE
Register plugin for caddy

### ISSUE THREAD

**Issue by fd0** [restic/caddy#1]
I've roughly looked at the process:
 * [x] We need to open a PR for caddy to correct the URL https://github.com/mholt/caddy/blob/7b5efb5d7581e7c6f04f000369708f5cf25e10f4/caddyhttp/httpserver/plugin.go#L498
 * [x] Register the plugin
 * [x] Tag a release so that the website includes it as an option

**Comment by mholt** [comment]
@fd0 Oops, I'll change the URL in just a bit -- do not worry about that! I've already changed it locally and will push the commit momentarily. So that step is done. All you have to do is tag a release and go to caddyserver.com to submit it. :+1:

**Comment by mholt** [comment]
To clarify, the comment with the package url is not used by the Caddy website, just is there for convenience. So you don't have to wait for a release of Caddy.

**Comment by fd0** [comment]
I've (finally) taken the steps required to publish the plugin. Thanks a lot!

**Comment by mholt** [comment]
Congrats, Alexander! Thanks so much for doing this. :tada:
