### ISSUE TITLE
Module contains incorrect path.

### ISSUE THREAD

**Issue by Kasheen** [restic/caddy#10]
**Description:**
https://github.com/restic/caddy/blob/d84442c3e531bfe28336f63f80d6651b74ea088c/go.mod#L1

As seen [go.mod](https://github.com/restic/caddy/blob/d84442c3e531bfe28336f63f80d6651b74ea088c/go.mod) has a mismatching module path in relation to this repository (presumably so that @tdralle could test their work using `xcaddy build` from their own repository).

As a result `xcaddy build --with github.com/restic/caddy@master` fails with:

> go: github.com/restic/caddy@v0.2.2-0.20240813031006-d84442c3e531 found: parsing go.mod:
> module declares its path as: github.com/tdralle/caddy
> but was required as: github.com/restic/caddy

**Proposed Fix**
Change line 1 of [go.mod](https://github.com/restic/caddy/blob/d84442c3e531bfe28336f63f80d6651b74ea088c/go.mod) to:

`module github.com/restic/caddy`

**Comment by mholt** [comment]
You're right, thank you!
