### ISSUE TITLE
Incompatible with caddy 1.0.0+

### ISSUE THREAD

**Issue by klingtnet** [restic/caddy#5]
This plugin breaks a caddy build with the following message:

```
.go/pkg/mod/github.com/restic/caddy@v0.2.1/setup.go:19:16: undefined: restserver.Server
.go/pkg/mod/github.com/restic/caddy@v0.2.1/setup.go:42:19: undefined: restserver.NewHandler
```

The issue is maybe related to caddy requiring Go modules to build since its 1.0.0. Introducing modules support is quite easy, simply run `go mod init github.com/restic/caddy` in the root of your repository and commit `go.sum` and `go.mod` that are created by the aforementioned command.

**Comment by klingtnet** [comment]
Related forum post: https://caddy.community/t/what-plugins-can-we-install-right-now/5618/4

**Comment by mholt** [comment]
Thanks, fixed with https://github.com/restic/rest-server/issues/77#issuecomment-491894849!
